import { defineArrayMember, defineField, defineType } from "sanity";
import { Info } from "lucide-react";

export const aboutPage = defineType({
  name: "aboutPage",
  title: "About page",
  type: "document",
  icon: Info,
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "body", title: "Body" },
    { name: "cta", title: "Call to action" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "heading",
      title: "Page heading",
      type: "array",
      group: "hero",
      of: [defineArrayMember({ type: "headingSegment" })],
      description: "The large heading at the top. Set the first segment's level to H1.",
    }),
    defineField({
      name: "intro",
      title: "Intro",
      type: "text",
      rows: 3,
      group: "hero",
      description: "The line under the heading, describing what this project is.",
    }),
    defineField({
      name: "missionTitle",
      title: "Mission heading",
      type: "string",
      group: "body",
      description: "Heading above the longer explanation, e.g. \"Project goal\".",
    }),
    defineField({
      name: "missionBody",
      title: "Mission body",
      type: "richText",
      group: "body",
      description: "The longer explanation of why this project exists.",
    }),
    defineField({
      name: "techStackTitle",
      title: "Tech stack heading",
      type: "string",
      group: "body",
    }),
    defineField({
      name: "techStack",
      title: "Tech stack",
      type: "array",
      group: "body",
      of: [
        defineArrayMember({
          type: "object",
          name: "techItem",
          fields: [
            defineField({
              name: "name",
              type: "string",
              title: "Name",
              description: "The tool, e.g. \"Next.js 16\".",
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: "description",
              type: "string",
              title: "What it does",
              description: "A few words, e.g. \"React framework with App Router\".",
            }),
          ],
          preview: { select: { title: "name", subtitle: "description" } },
        }),
      ],
      description: "Shown as a grid. Keep entries short — this is a scan, not a reading exercise.",
    }),
    defineField({
      name: "keyFeaturesTitle",
      title: "Key features heading",
      type: "string",
      group: "body",
    }),
    defineField({
      name: "keyFeatures",
      title: "Key features",
      type: "array",
      group: "body",
      of: [defineArrayMember({ type: "string" })],
      description: "A short bulleted list of what the platform does.",
    }),
    defineField({
      name: "openSourceTitle",
      title: "Open source heading",
      type: "string",
      group: "body",
    }),
    defineField({
      name: "openSourceBody",
      title: "Open source body",
      type: "richText",
      group: "body",
    }),
    defineField({
      name: "openSourceBadges",
      title: "Concept badges",
      type: "array",
      group: "body",
      of: [defineArrayMember({ type: "string" })],
      description: "Small pills naming the patterns demonstrated, e.g. \"Server Components\".",
    }),
    defineField({
      name: "repositoryCta",
      title: "Repository button",
      type: "ctaBtn",
      group: "body",
      description: "Links to the source. Leave empty and no button renders.",
    }),
    defineField({
      name: "ctaTitle",
      title: "Closing heading",
      type: "string",
      group: "cta",
    }),
    defineField({
      name: "ctaSubtitle",
      title: "Closing text",
      type: "text",
      rows: 2,
      group: "cta",
    }),
    defineField({
      name: "ctaButtons",
      title: "Closing buttons",
      type: "array",
      group: "cta",
      of: [defineArrayMember({ type: "ctaBtn" })],
      validation: (Rule) => Rule.max(2).warning("Two buttons at most — more and neither gets pressed."),
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "About page" }) },
});
